In [75]:
import sqlite3
import pandas as pd 
con = sqlite3.connect('../data/raw/ipl.db')

In [76]:
def query(sql):
   return pd.read_sql(sql,con)

In [77]:
def run_sql_file(path):
    with open(path,'r')as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [78]:
query('SELECT COUNT(*)FROM matches;')

   COUNT(*)
0      1212

In [79]:
query('''SELECT COUNT (*)AS looks_empty
FROM matches
WHERE player_of_match = '';''')

   looks_empty
0            9

In [80]:
query('''SELECT CoUnT(*)AS found_by_is_null
FROM matches
WHERE player_of_match IS NULL;''')

   found_by_is_null
0                 0

In [81]:
query('''
SELECT length (bowler_type)AS len,COUNT(*) AS rows
fROM deliveries
WHERE bowler_type IS NULL OR TRIM (bowler_type)=''
GROUP BY len;''')

   len  rows
0  NaN   339
1  1.0     8

In [82]:
query('''
SELECT TRIM( '  hello  ' ) AS trimmed,
    LENGTH( '  hello  ') AS before,
    LENGTH(TRIM(' hello ')) AS after;''')

  trimmed  before  after
0   hello       9      5

In [83]:
query('''
SELECT NULLIF('a', 'a') AS same,
       NULLIF('a', 'b') AS different,
       NULLIF('', '') AS empty;''')

   same different empty
0  None         a  None

In [90]:
run_sql_file('../sql/01_nulls_and_blanks.sql')

ran ../sql/01_nulls_and_blanks.sql

In [91]:
query('''
SELECT COUNT(*) AS blank_before
FROM deliveries
WHERE TRIM(bowler_type) = '';''')

   blank_before
0             8

In [92]:
query('''
SELECT COUNT(*) AS null_after
FROM v_players_clean
WHERE field_pos_clean IS NULL;''')

   null_after
0         700