QUESTION PAPER-1

In [15]:
import pandas as pd
import sqlite3
con = sqlite3.connect("C:/Users/afnaa/OneDrive/Documents/OJT SEM 3/ipl-cricket-analytics/ipl-cricket-analytics/data/raw/ipl.db")
def q(sql):
    return pd.read_sql(sql,con)

In [21]:
q('''
SELECT match_id,venue
FROM matches
limit 10;
''')

   match_id                                      venue
0    335982                      M Chinnaswamy Stadium
1   1082591  Rajiv Gandhi International Stadium, Uppal
2   1082592    Maharashtra Cricket Association Stadium
3   1082593     Saurashtra Cricket Association Stadium
4   1082594                     Holkar Cricket Stadium
5   1082595                      M.Chinnaswamy Stadium
6   1082596  Rajiv Gandhi International Stadium, Uppal
7   1082597                           Wankhede Stadium
8   1082598                     Holkar Cricket Stadium
9   1082599    Maharashtra Cricket Association Stadium

SELECT- choose the columns.
FROM-choose the table.
A row- show 10 rows.

QUESTION-2

This query shows all the different seasons from the matches table.

It does not show the same season more than once

In [23]:
q('''
SELECT DISTINCT season 
FROM matches;
''')

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [24]:
q('''
SELECT match_id,city
FROM matches
WHERE city='Mumbai';
''')

     match_id    city
0     1082597  Mumbai
1     1082600  Mumbai
2     1082606  Mumbai
3     1082614  Mumbai
4     1082618  Mumbai
..        ...     ...
180   1527675  Mumbai
181   1527693  Mumbai
182   1529267  Mumbai
183   1529276  Mumbai
184   1529284  Mumbai

[185 rows x 2 columns]

In [25]:
q('''SELECT COUNT(*) AS total_matches
FROM matches;
''')

   total_matches
0           1212

SELECT = choose data
FROM = choose table
WHERE = condition,filter
DISTINCT = remove duplicates
COUNT(*) = count rows
AS = give name
LIMIT 10 = show 10 rows